# Validate that listener-level invalid policy on XListenerSet listener
# reports to the specific listener and doesn't affect other listeners.
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: example-gateway
  namespace: gwtest
spec:
  gatewayClassName: kgateway
  listeners:
  - name: http-8080
    protocol: HTTP
    port: 8080
  allowedListeners:
    namespaces:
      from: All
---
apiVersion: gateway.networking.x-k8s.io/v1alpha1
kind: XListenerSet
metadata:
  name: test-listenerset
  namespace: gwtest
spec:
  parentRef:
    name: example-gateway
    kind: Gateway
    group: gateway.networking.k8s.io
  listeners:
  - name: http-9090
    protocol: HTTP
    port: 9090
    allowedRoutes:
      namespaces:
        from: All
  - name: https-8443
    protocol: HTTPS
    port: 8443
    allowedRoutes:
      namespaces:
        from: All
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: test-route
  namespace: gwtest
spec:
  parentRefs:
  - name: test-listenerset
    group: gateway.networking.x-k8s.io
    kind: XListenerSet
  hostnames:
  - "www.example.com"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: example-svc
      port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: example-svc
  namespace: gwtest
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: example
---
apiVersion: gateway.kgateway.dev/v1alpha1
kind: TrafficPolicy
metadata:
  name: invalid-traffic-policy
  namespace: gwtest
spec:
  targetRefs:
  - name: test-listenerset
    group: gateway.networking.x-k8s.io
    kind: XListenerSet
    sectionName: http-9090
  transformation:
    request:
      body:
        parseAs: AsJson
        value: "{{ invalid_template }"
