// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ExtAuthBufferSettingsApplyConfiguration represents a declarative configuration of the ExtAuthBufferSettings type for use
// with apply.
type ExtAuthBufferSettingsApplyConfiguration struct {
	MaxRequestBytes     *int32 `json:"maxRequestBytes,omitempty"`
	AllowPartialMessage *bool  `json:"allowPartialMessage,omitempty"`
	PackAsBytes         *bool  `json:"packAsBytes,omitempty"`
}

// ExtAuthBufferSettingsApplyConfiguration constructs a declarative configuration of the ExtAuthBufferSettings type for use with
// apply.
func ExtAuthBufferSettings() *ExtAuthBufferSettingsApplyConfiguration {
	return &ExtAuthBufferSettingsApplyConfiguration{}
}

// WithMaxRequestBytes sets the MaxRequestBytes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxRequestBytes field is set to the value of the last call.
func (b *ExtAuthBufferSettingsApplyConfiguration) WithMaxRequestBytes(value int32) *ExtAuthBufferSettingsApplyConfiguration {
	b.MaxRequestBytes = &value
	return b
}

// WithAllowPartialMessage sets the AllowPartialMessage field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AllowPartialMessage field is set to the value of the last call.
func (b *ExtAuthBufferSettingsApplyConfiguration) WithAllowPartialMessage(value bool) *ExtAuthBufferSettingsApplyConfiguration {
	b.AllowPartialMessage = &value
	return b
}

// WithPackAsBytes sets the PackAsBytes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PackAsBytes field is set to the value of the last call.
func (b *ExtAuthBufferSettingsApplyConfiguration) WithPackAsBytes(value bool) *ExtAuthBufferSettingsApplyConfiguration {
	b.PackAsBytes = &value
	return b
}
