// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// MetadataOptionsApplyConfiguration represents a declarative configuration of the MetadataOptions type for use
// with apply.
type MetadataOptionsApplyConfiguration struct {
	Forwarding *MetadataNamespacesApplyConfiguration `json:"forwarding,omitempty"`
}

// MetadataOptionsApplyConfiguration constructs a declarative configuration of the MetadataOptions type for use with
// apply.
func MetadataOptions() *MetadataOptionsApplyConfiguration {
	return &MetadataOptionsApplyConfiguration{}
}

// WithForwarding sets the Forwarding field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Forwarding field is set to the value of the last call.
func (b *MetadataOptionsApplyConfiguration) WithForwarding(value *MetadataNamespacesApplyConfiguration) *MetadataOptionsApplyConfiguration {
	b.Forwarding = value
	return b
}
