// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// RBACPolicyApplyConfiguration represents a declarative configuration of the RBACPolicy type for use
// with apply.
type RBACPolicyApplyConfiguration struct {
	MatchExpressions []string `json:"matchExpressions,omitempty"`
}

// RBACPolicyApplyConfiguration constructs a declarative configuration of the RBACPolicy type for use with
// apply.
func RBACPolicy() *RBACPolicyApplyConfiguration {
	return &RBACPolicyApplyConfiguration{}
}

// WithMatchExpressions adds the given value to the MatchExpressions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the MatchExpressions field.
func (b *RBACPolicyApplyConfiguration) WithMatchExpressions(values ...string) *RBACPolicyApplyConfiguration {
	for i := range values {
		b.MatchExpressions = append(b.MatchExpressions, values[i])
	}
	return b
}
