name: Performance Tests
description: Runs tests with the performance label

runs:
  using: "composite"
  steps:
  - name: Testing - performance tests
    shell: bash
    run: make install-test-tools run-performance-tests
  - uses: actions/upload-artifact@v4
    if: ${{ failure() }}
    with:
      name: performance-dump-attempt-${{ github.run_attempt }}
      path: "_output/performance-artifacts"
      if-no-files-found: warn