extraEnvVars:
  - name: LS_LOG
    value: debug
debug: true
mountDind:
  enabled: true
  forceTLS: true
  image: "docker:26-dind"
startServices: "lambda"
volumes:
  - name: docker-sock
    hostPath:
      path: /var/run/docker.sock
volumeMounts:
  - name: docker-sock
    mountPath: /var/run/docker.sock
