kind: Gateway
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: gw
spec:
  gatewayClassName: kgateway
  listeners:
    - protocol: HTTP
      port: 8080
      name: http
      allowedRoutes:
        namespaces:
          from: Same
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: example-route
spec:
  parentRefs:
    - name: gw
  hostnames:
    - "example.com"
  rules:
    - backendRefs:
        - name: azure-upstream
          kind: Upstream
          group: gloo.solo.io
          filters:
            - type: ExtensionRef
              extensionRef:
                group: gloo.solo.io
                kind: Parameter
                name: uppercase
---
apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: azure-upstream
spec:
  azure:
    functionAppName: app-name
    functions:
      - functionName: uppercase